//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreBuy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreBuy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart/AddToCart.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.29.239:8084/api/.
        /// </summary>
        internal static string APIPrefix {
            get {
                return ResourceManager.GetString("APIPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Available : .
        /// </summary>
        internal static string AvailableItems {
            get {
                return ResourceManager.GetString("AvailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Added To Cart.
        /// </summary>
        internal static string CartAddMsg {
            get {
                return ResourceManager.GetString("CartAddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Add Cart.
        /// </summary>
        internal static string CartErrorMsg {
            get {
                return ResourceManager.GetString("CartErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CartItemCount.
        /// </summary>
        internal static string CartItemCount {
            get {
                return ResourceManager.GetString("CartItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Quantity.
        /// </summary>
        internal static string CartUpdateMsg {
            get {
                return ResourceManager.GetString("CartUpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId.
        /// </summary>
        internal static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/ChangePassword.
        /// </summary>
        internal static string ChangePasswordURI {
            get {
                return ResourceManager.GetString("ChangePasswordURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sblw-3hn8-sqoy19.
        /// </summary>
        internal static string CryptoKey {
            get {
                return ResourceManager.GetString("CryptoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MMMM-yyyy HH:mm.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DefaultIntValue {
            get {
                return ResourceManager.GetString("DefaultIntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string DefaultStringValue {
            get {
                return ResourceManager.GetString("DefaultStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cart/DeleteCartItem.
        /// </summary>
        internal static string DeleteCartItem {
            get {
                return ResourceManager.GetString("DeleteCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.. please login or else try register with different mail.
        /// </summary>
        internal static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Not supported on this device.
        /// </summary>
        internal static string FeatureErrorMsg {
            get {
                return ResourceManager.GetString("FeatureErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreSearch/FindStoresByDistance?UserId=.
        /// </summary>
        internal static string FindStoreByDistanceURI {
            get {
                return ResourceManager.GetString("FindStoreByDistanceURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreSearch/FindStoresByItems?UserId=.
        /// </summary>
        internal static string FindStoreByItemsURI {
            get {
                return ResourceManager.GetString("FindStoreByItemsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordMail.
        /// </summary>
        internal static string ForgotPasswordMail {
            get {
                return ResourceManager.GetString("ForgotPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/ForgotPassword.
        /// </summary>
        internal static string ForgotPasswordURI {
            get {
                return ResourceManager.GetString("ForgotPasswordURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart/CartItems?UserId=.
        /// </summary>
        internal static string GetCartItems {
            get {
                return ResourceManager.GetString("GetCartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to itemcategory/getallitemcategories.
        /// </summary>
        internal static string GetCategoryItems {
            get {
                return ResourceManager.GetString("GetCategoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Date=.
        /// </summary>
        internal static string GetDate {
            get {
                return ResourceManager.GetString("GetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slot/GetFilledSlots?StoreId=.
        /// </summary>
        internal static string GetFilledSlots {
            get {
                return ResourceManager.GetString("GetFilledSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/CategoryRelatedItems?CategoryId=.
        /// </summary>
        internal static string GetItemsOfCategory {
            get {
                return ResourceManager.GetString("GetItemsOfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order/GetOrdersByUser?UserId=.
        /// </summary>
        internal static string GetOrders {
            get {
                return ResourceManager.GetString("GetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;UserId=.
        /// </summary>
        internal static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/GetUserByUserName?UserName=.
        /// </summary>
        internal static string GetUserByUserNameURI {
            get {
                return ResourceManager.GetString("GetUserByUserNameURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemId.
        /// </summary>
        internal static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/SearchRelatedItems?SearchString=.
        /// </summary>
        internal static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Latitude=.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Not Enabled on this device.
        /// </summary>
        internal static string LocationEnableMsg {
            get {
                return ResourceManager.GetString("LocationEnableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Get Location on this device.
        /// </summary>
        internal static string LocationErrorMsg {
            get {
                return ResourceManager.GetString("LocationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/UserLogin.
        /// </summary>
        internal static string LoginURI {
            get {
                return ResourceManager.GetString("LoginURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Longitude=.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Send the Mail.
        /// </summary>
        internal static string MailErrorMsg {
            get {
                return ResourceManager.GetString("MailErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id Doesn&apos;t Exist.
        /// </summary>
        internal static string NoEmailExist {
            get {
                return ResourceManager.GetString("NoEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Found.
        /// </summary>
        internal static string NoLocationErrorMsg {
            get {
                return ResourceManager.GetString("NoLocationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPassword.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is not correct.
        /// </summary>
        internal static string OldPasswordMsg {
            get {
                return ResourceManager.GetString("OldPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPReceived.
        /// </summary>
        internal static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Expired.
        /// </summary>
        internal static string OtpExpired {
            get {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code in Correct Format.
        /// </summary>
        internal static string OtpFormatMsg {
            get {
                return ResourceManager.GetString("OtpFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/VerifyOTP.
        /// </summary>
        internal static string OTPVerifyURI {
            get {
                return ResourceManager.GetString("OTPVerifyURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the correct code.
        /// </summary>
        internal static string OtpWrong {
            get {
                return ResourceManager.GetString("OtpWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password.
        /// </summary>
        internal static string PasswordErrorMsg {
            get {
                return ResourceManager.GetString("PasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords didn&apos;t match.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed successfully....
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.. Please Login...
        /// </summary>
        internal static string PasswordUpdatedLogin {
            get {
                return ResourceManager.GetString("PasswordUpdatedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string PermissionMsg {
            get {
                return ResourceManager.GetString("PermissionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order/InsertOrder.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Registered.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register please try later.
        /// </summary>
        internal static string RegisterUnsuccess {
            get {
                return ResourceManager.GetString("RegisterUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/ResetPassword.
        /// </summary>
        internal static string ResetPasswordURI {
            get {
                return ResourceManager.GetString("ResetPasswordURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.29.239/.
        /// </summary>
        internal static string RGWIP {
            get {
                return ResourceManager.GetString("RGWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlotDate.
        /// </summary>
        internal static string SlotDate {
            get {
                return ResourceManager.GetString("SlotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKING SLOT SUCCESSFULL.
        /// </summary>
        internal static string SlotSuccess {
            get {
                return ResourceManager.GetString("SlotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlotTime.
        /// </summary>
        internal static string SlotTime {
            get {
                return ResourceManager.GetString("SlotTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string SlotTimeFormat {
            get {
                return ResourceManager.GetString("SlotTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKING SLOT UNSUCCESSFULL.
        /// </summary>
        internal static string SlotUnsuccess {
            get {
                return ResourceManager.GetString("SlotUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreId.
        /// </summary>
        internal static string StoreId {
            get {
                return ResourceManager.GetString("StoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/common/uikitimages/.
        /// </summary>
        internal static string SyncFusion {
            get {
                return ResourceManager.GetString("SyncFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields Can&apos;t be Empty.
        /// </summary>
        internal static string TextBoxEmpty {
            get {
                return ResourceManager.GetString("TextBoxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart/UpdateQuantity.
        /// </summary>
        internal static string UpdateItemQuantity {
            get {
                return ResourceManager.GetString("UpdateItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/UserCheck.
        /// </summary>
        internal static string UserCheck {
            get {
                return ResourceManager.GetString("UserCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFirstName.
        /// </summary>
        internal static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFullName.
        /// </summary>
        internal static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPhone.
        /// </summary>
        internal static string UserPhone {
            get {
                return ResourceManager.GetString("UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/UserRegister.
        /// </summary>
        internal static string UserRegisterURI {
            get {
                return ResourceManager.GetString("UserRegisterURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are Wrong.
        /// </summary>
        internal static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
